owner: gfxpronet
repo: upptime
user-agent: gfxpronet

sites:
  - name: GFX Productions™
    url: https://gfx-pro.net
    icon: https://api.gfx-pro.net/gpn.ico
  - name: GFX Productions™ API
    url: https://api.gfx-pro.net
    icon: 
  - name: GFX Productions™ Legal
    url: https://legal.gfx-pro.net
    icon: 
  - name: MediaKiller™
    url: https://mk.gfx-pro.net
    icon: https://api.gfx-pro.net/img/mk.ico
  - name: PlayMusic™
    url: https://music.gfxp.ro
    icon: https://api.gfx-pro.net/img/playmusic.ico
  - name: Pokémon GO Profiles
    url: https://pgo.gfxp.ro
    icon: https://api.gfx-pro.net/img/pgo.ico
  - name: Pokémon GO Shiny Hunt
    url: https://api.gfx-pro.net/assets/shinyHunt/v2/
    icon: 
  - name: Pokémon GO Shiny Rates
    url: https://api.gfx-pro.net/assets/shinyRates
    icon: https://api.gfx-pro.net/img/pgo.ico
  - name: Redirected by GPN™
    url: https://gfxp.ro
    icon: 
  - name: RGB24/BGR15 Converter
    url: https://api.gfx-pro.net/assets/BGR15
    icon: https://colorslurp.com/images/app-icon.png

status-website:
  #cname: status.gfx-pro.net
  baseUrl: /upptime
  theme: night
  favicon: https://api.gfx-pro.net/gpn.ico
  logoUrl: https://legal.gfx-pro.net/uploads/9/5/4/7/9547383/published/standard-white_10.png
  name: GFX | Productions™
  introTitle: ""
  introMessage: 
  customHeadHtml: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "⠀"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */3 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
