owner: gfxpronet
repo: upptime
user-agent: gfxpronet

sites:
  - name: GFX | Productions™
    url: https://gfx-pro.net
    icon: https://api.gfx-pro.net/gpn.ico
  - name: GFX | Productions™ API
    url: https://api.gfx-pro.net
    icon: 
  - name: GFX | Productions™ Legal
    url: https://legal.gfx-pro.net
    icon: 
  - name: MediaKiller™
    url: https://mk.gfx-pro.net
    icon: https://api.gfx-pro.net/img/mk.ico
  - name: PlayMusic™
    url: https://music.gfxp.ro
    icon: https://api.gfx-pro.net/img/playmusic.ico
  - name: Redirected by GPN™
    url: https://gfxp.ro
    icon: 

status-website:
  #cname: status.gfx-pro.net
  baseUrl: /upptime
  theme: night
  favicon: https://api.gfx-pro.net/gpn.ico
  logoUrl: https://legal.gfx-pro.net/uploads/9/5/4/7/9547383/published/standard-white_10.png
  name: GFX | Productions™
  introTitle: ""
  introMessage: 
  customHeadHtml: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "©2023 GFX | Productions™. Trademarks belong to their respective owners, All Rights Reserved."

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */1 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
