owner: gfxpronet
repo: upptime

sites:
  - name: GFX | Productions™
    url: https://gfx-pro.net
    icon: https://api.gfx-pro.net/gpn.ico
  - name: GFX | Productions™ API
    url: https://api.gfx-pro.net
    icon: 
  - name: GFX | Productions™ Legal
    url: https://legal.gfx-pro.net
    icon: https://api.gfx-pro.net/gpn.ico

status-website:
  #cname: status.gfx-pro.net
  baseUrl: /upptime
  theme: night
  favicon: https://api.gfx-pro.net/gpn.ico
  logoUrl: https://legal.gfx-pro.net/uploads/9/5/4/7/9547383/published/standard-white_10.png
  name: GFX | Productions™
  introTitle: ""
  introMessage: 
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  responseTime: "0 */1 * * *"
